### ISSUE TITLE
Performance Enhancement - Use LOAD FP INTEGER for math.floor() and math.ceil()

### ISSUE THREAD

**Issue by joncmu** [linux-on-ibm-z/go#3]
To mimic the assembly done for amd64 LOAD FP INTEGER can be used for the floor and ceil functions with round toward zero selected for floor.  For ceil you will need to do a LCDBR, FIDBRA, LCDBR since there is not a round away from zero mode.

**Comment by joransiu** [comment]
How does floor/ceiling behave in GO?  For JavaScript, Math.floor rounds towards negative infinity, Math.ceil rounds towards postive infinity.

The Math.ceil() function returns the smallest integer greater than or equal to a given number.
The Math.floor() function returns the largest integer less than or equal to a given number.

```
> Math.ceil(-0.5)
-0
> Math.floor(-0.5)
-1
```

**Comment by joncmu** [comment]
https://golang.org/pkg/math/#Ceil
Ceil returns the least integer value greater than or equal to x.

https://golang.org/pkg/math/#Floor
Floor returns the greatest integer value less than or equal to x.

Ok, so it looks like you can just use round to +inf or round -inf.

**Comment by joransiu** [comment]
Thanks for the links @joncmu.   That's consistent with JavaScript.   So Ceil should round to +Inf, Floor should round to -Inf, and there are matching modes for both of those under FIDBRA.

**Comment by mundaym** [comment]
Thanks @joncmu. Added this in https://github.com/linux-on-ibm-z/go/commit/def14f62f5434ee32dd5f8cd9347d09369a5bf29. Will be upstreamed once the tree re-opens.
